"""empty message

Revision ID: 8f4d38c6d608
Revises: 5f2a61f685be
Create Date: 2022-07-13 17:01:08.271259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f4d38c6d608'
down_revision = '5f2a61f685be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answer', sa.Column('reply_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('answer', 'reply_id')
    # ### end Alembic commands ###
